/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface DoubtEntry {
  'id' : string,
  'status' : DoubtStatus,
  'question' : string,
  'exerciseRef' : [] | [string],
  'owner' : Principal,
  'solution' : string,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type DoubtStatus = { 'in_progress' : null } |
  { 'answered' : null } |
  { 'not_answered' : null };
export interface Exercise {
  'id' : string,
  'question' : string,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'level' : Level,
  'solution' : string,
}
export type ExternalBlob = Uint8Array;
export type Level = { 'elementary' : null } |
  { 'high' : null } |
  { 'middle' : null };
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'imageId' : [] | [ExternalBlob],
  'topicId' : [] | [string],
}
export type Subject = { 'biology' : null } |
  { 'nature_in_society' : null } |
  { 'economy' : null } |
  { 'arts' : null } |
  { 'world_orientation' : null } |
  { 'history' : null } |
  { 'geography' : null } |
  { 'chemistry' : null } |
  { 'german' : null } |
  { 'mathematics' : null } |
  { 'social_studies' : null } |
  { 'physics' : null } |
  { 'english' : null };
export type Time = bigint;
export interface UserProfile {
  'subjects' : Array<Subject>,
  'savedNotes' : Array<string>,
  'name' : string,
  'learningHistory' : Array<string>,
  'classLevel' : Level,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'subject' : Subject,
  'video' : ExternalBlob,
  'name' : string,
  'level' : Level,
  'solution' : ExternalBlob,
  'lesson' : ExternalBlob,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'answerDoubt' : ActorMethod<[string, string, DoubtStatus], DoubtEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachImageToNote' : ActorMethod<[string, ExternalBlob], undefined>,
  'createExercise' : ActorMethod<
    [string, string, Subject, Level, Difficulty],
    Exercise
  >,
  'createNote' : ActorMethod<[string, string, [] | [string]], Note>,
  'createTopic' : ActorMethod<[string, string], undefined>,
  'createVideo' : ActorMethod<
    [string, string, Subject, Level, ExternalBlob, ExternalBlob, ExternalBlob],
    undefined
  >,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllTopics' : ActorMethod<[], Array<[string, string]>>,
  'getCallerDoubtHistory' : ActorMethod<[], Array<DoubtEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoubt' : ActorMethod<[string], DoubtEntry>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getRelevantDoubts' : ActorMethod<[], Array<DoubtEntry>>,
  'getRelevantExercises' : ActorMethod<[Subject, Level], Array<Exercise>>,
  'getRelevantVideos' : ActorMethod<[Subject, Level], Array<Video>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDoubt' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string]],
    DoubtEntry
  >,
  'updateNote' : ActorMethod<[string, string, string, [] | [string]], Note>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];