/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DoubtStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'answered' : IDL.Null,
  'not_answered' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DoubtEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : DoubtStatus,
  'question' : IDL.Text,
  'exerciseRef' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'solution' : IDL.Text,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'biology' : IDL.Null,
  'nature_in_society' : IDL.Null,
  'economy' : IDL.Null,
  'arts' : IDL.Null,
  'world_orientation' : IDL.Null,
  'history' : IDL.Null,
  'geography' : IDL.Null,
  'chemistry' : IDL.Null,
  'german' : IDL.Null,
  'mathematics' : IDL.Null,
  'social_studies' : IDL.Null,
  'physics' : IDL.Null,
  'english' : IDL.Null,
});
export const Level = IDL.Variant({
  'elementary' : IDL.Null,
  'high' : IDL.Null,
  'middle' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'level' : Level,
  'solution' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'imageId' : IDL.Opt(ExternalBlob),
  'topicId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'savedNotes' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'learningHistory' : IDL.Vec(IDL.Text),
  'classLevel' : Level,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'subject' : Subject,
  'video' : ExternalBlob,
  'name' : IDL.Text,
  'level' : Level,
  'solution' : ExternalBlob,
  'lesson' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'answerDoubt' : IDL.Func([IDL.Text, IDL.Text, DoubtStatus], [DoubtEntry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachImageToNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'createExercise' : IDL.Func(
      [IDL.Text, IDL.Text, Subject, Level, Difficulty],
      [Exercise],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [Note], []),
  'createTopic' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Subject,
        Level,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
      ],
      [],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllTopics' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCallerDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoubt' : IDL.Func([IDL.Text], [DoubtEntry], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getRelevantDoubts' : IDL.Func([], [IDL.Vec(DoubtEntry)], ['query']),
  'getRelevantExercises' : IDL.Func(
      [Subject, Level],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getRelevantVideos' : IDL.Func([Subject, Level], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDoubt' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [DoubtEntry],
      [],
    ),
  'updateNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Note],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DoubtStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'answered' : IDL.Null,
    'not_answered' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DoubtEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : DoubtStatus,
    'question' : IDL.Text,
    'exerciseRef' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'solution' : IDL.Text,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'biology' : IDL.Null,
    'nature_in_society' : IDL.Null,
    'economy' : IDL.Null,
    'arts' : IDL.Null,
    'world_orientation' : IDL.Null,
    'history' : IDL.Null,
    'geography' : IDL.Null,
    'chemistry' : IDL.Null,
    'german' : IDL.Null,
    'mathematics' : IDL.Null,
    'social_studies' : IDL.Null,
    'physics' : IDL.Null,
    'english' : IDL.Null,
  });
  const Level = IDL.Variant({
    'elementary' : IDL.Null,
    'high' : IDL.Null,
    'middle' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'subject' : Subject,
    'difficulty' : Difficulty,
    'level' : Level,
    'solution' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'imageId' : IDL.Opt(ExternalBlob),
    'topicId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'savedNotes' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'learningHistory' : IDL.Vec(IDL.Text),
    'classLevel' : Level,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'subject' : Subject,
    'video' : ExternalBlob,
    'name' : IDL.Text,
    'level' : Level,
    'solution' : ExternalBlob,
    'lesson' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'answerDoubt' : IDL.Func(
        [IDL.Text, IDL.Text, DoubtStatus],
        [DoubtEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachImageToNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'createExercise' : IDL.Func(
        [IDL.Text, IDL.Text, Subject, Level, Difficulty],
        [Exercise],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Note],
        [],
      ),
    'createTopic' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Subject,
          Level,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
        ],
        [],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllTopics' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCallerDoubtHistory' : IDL.Func([], [IDL.Vec(DoubtEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoubt' : IDL.Func([IDL.Text], [DoubtEntry], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getRelevantDoubts' : IDL.Func([], [IDL.Vec(DoubtEntry)], ['query']),
    'getRelevantExercises' : IDL.Func(
        [Subject, Level],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getRelevantVideos' : IDL.Func(
        [Subject, Level],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDoubt' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [DoubtEntry],
        [],
      ),
    'updateNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Note],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };