/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: string;
    subject: Subject;
    video: ExternalBlob;
    name: string;
    level: Level;
    solution: ExternalBlob;
    lesson: ExternalBlob;
}
export interface Exercise {
    id: string;
    question: string;
    subject: Subject;
    difficulty: Difficulty;
    level: Level;
    solution: string;
}
export interface UserProfile {
    subjects: Array<Subject>;
    savedNotes: Array<string>;
    name: string;
    learningHistory: Array<string>;
    classLevel: Level;
}
export type Time = bigint;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DoubtEntry {
    id: string;
    status: DoubtStatus;
    question: string;
    exerciseRef?: string;
    owner: Principal;
    solution: string;
    timestamp: Time;
    image?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Note {
    id: string;
    title: string;
    content: string;
    owner: Principal;
    imageId?: ExternalBlob;
    topicId?: string;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum DoubtStatus {
    in_progress = "in_progress",
    answered = "answered",
    not_answered = "not_answered"
}
export enum Level {
    elementary = "elementary",
    high = "high",
    middle = "middle"
}
export enum Subject {
    biology = "biology",
    nature_in_society = "nature_in_society",
    economy = "economy",
    arts = "arts",
    world_orientation = "world_orientation",
    history = "history",
    geography = "geography",
    chemistry = "chemistry",
    german = "german",
    mathematics = "mathematics",
    social_studies = "social_studies",
    physics = "physics",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    answerDoubt(doubtId: string, solution: string, status: DoubtStatus): Promise<DoubtEntry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attachImageToNote(noteId: string, image: ExternalBlob): Promise<void>;
    createExercise(_question: string, _solution: string, _subject: Subject, _level: Level, _difficulty: Difficulty): Promise<Exercise>;
    createNote(title: string, content: string, topicId: string | null): Promise<Note>;
    createTopic(_id: string, _name: string): Promise<void>;
    createVideo(_id: string, _name: string, _subject: Subject, _level: Level, _video: ExternalBlob, _lesson: ExternalBlob, _solution: ExternalBlob): Promise<void>;
    deleteNote(id: string): Promise<void>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllTopics(): Promise<Array<[string, string]>>;
    getCallerDoubtHistory(): Promise<Array<DoubtEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoubt(_doubtId: string): Promise<DoubtEntry>;
    getNotes(): Promise<Array<Note>>;
    getRelevantDoubts(): Promise<Array<DoubtEntry>>;
    getRelevantExercises(_subject: Subject, _level: Level): Promise<Array<Exercise>>;
    getRelevantVideos(_subject: Subject, _level: Level): Promise<Array<Video>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitDoubt(question: string, image: ExternalBlob | null, exerciseRef: string | null): Promise<DoubtEntry>;
    updateNote(id: string, newTitle: string, newContent: string, newTopicId: string | null): Promise<Note>;
}
import type { Difficulty as _Difficulty, DoubtEntry as _DoubtEntry, DoubtStatus as _DoubtStatus, Exercise as _Exercise, ExternalBlob as _ExternalBlob, Level as _Level, Note as _Note, Subject as _Subject, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async answerDoubt(arg0: string, arg1: string, arg2: DoubtStatus): Promise<DoubtEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.answerDoubt(arg0, arg1, to_candid_DoubtStatus_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerDoubt(arg0, arg1, to_candid_DoubtStatus_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attachImageToNote(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.attachImageToNote(arg0, await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attachImageToNote(arg0, await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createExercise(arg0: string, arg1: string, arg2: Subject, arg3: Level, arg4: Difficulty): Promise<Exercise> {
        if (this.processError) {
            try {
                const result = await this.actor.createExercise(arg0, arg1, to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n24(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Exercise_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExercise(arg0, arg1, to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n24(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Exercise_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: string, arg2: string | null): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Note_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Note_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTopic(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTopic(arg0, arg1);
            return result;
        }
    }
    async createVideo(arg0: string, arg1: string, arg2: Subject, arg3: Level, arg4: ExternalBlob, arg5: ExternalBlob, arg6: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(arg0, arg1, to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(arg0, arg1, to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg2), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTopics(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTopics();
            return result;
        }
    }
    async getCallerDoubtHistory(): Promise<Array<DoubtEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDoubtHistory();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDoubtHistory();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoubt(arg0: string): Promise<DoubtEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubt(arg0);
                return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubt(arg0);
            return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelevantDoubts(): Promise<Array<DoubtEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelevantDoubts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelevantDoubts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelevantExercises(arg0: Subject, arg1: Level): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelevantExercises(to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg0), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelevantExercises(to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg0), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelevantVideos(arg0: Subject, arg1: Level): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelevantVideos(to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg0), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelevantVideos(to_candid_Subject_n20(this._uploadFile, this._downloadFile, arg0), to_candid_Level_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDoubt(arg0: string, arg1: ExternalBlob | null, arg2: string | null): Promise<DoubtEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoubt(arg0, await to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoubt(arg0, await to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_DoubtEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Note_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Note_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Difficulty_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_DoubtEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoubtEntry): Promise<DoubtEntry> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DoubtStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoubtStatus): DoubtStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Level_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_Note_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Promise<Note> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DoubtStatus;
    question: string;
    exerciseRef: [] | [string];
    owner: Principal;
    solution: string;
    timestamp: _Time;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    status: DoubtStatus;
    question: string;
    exerciseRef?: string;
    owner: Principal;
    solution: string;
    timestamp: Time;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_DoubtStatus_n12(_uploadFile, _downloadFile, value.status),
        question: value.question,
        exerciseRef: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.exerciseRef)),
        owner: value.owner,
        solution: value.solution,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    question: string;
    subject: _Subject;
    difficulty: _Difficulty;
    level: _Level;
    solution: string;
}): {
    id: string;
    question: string;
    subject: Subject;
    difficulty: Difficulty;
    level: Level;
    solution: string;
} {
    return {
        id: value.id,
        question: value.question,
        subject: from_candid_Subject_n28(_uploadFile, _downloadFile, value.subject),
        difficulty: from_candid_Difficulty_n30(_uploadFile, _downloadFile, value.difficulty),
        level: from_candid_Level_n32(_uploadFile, _downloadFile, value.level),
        solution: value.solution
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    owner: Principal;
    imageId: [] | [_ExternalBlob];
    topicId: [] | [string];
}): Promise<{
    id: string;
    title: string;
    content: string;
    owner: Principal;
    imageId?: ExternalBlob;
    topicId?: string;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        owner: value.owner,
        imageId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.imageId)),
        topicId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.topicId))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_Subject>;
    savedNotes: Array<string>;
    name: string;
    learningHistory: Array<string>;
    classLevel: _Level;
}): {
    subjects: Array<Subject>;
    savedNotes: Array<string>;
    name: string;
    learningHistory: Array<string>;
    classLevel: Level;
} {
    return {
        subjects: from_candid_vec_n42(_uploadFile, _downloadFile, value.subjects),
        savedNotes: value.savedNotes,
        name: value.name,
        learningHistory: value.learningHistory,
        classLevel: from_candid_Level_n32(_uploadFile, _downloadFile, value.classLevel)
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: _Subject;
    video: _ExternalBlob;
    name: string;
    level: _Level;
    solution: _ExternalBlob;
    lesson: _ExternalBlob;
}): Promise<{
    id: string;
    subject: Subject;
    video: ExternalBlob;
    name: string;
    level: Level;
    solution: ExternalBlob;
    lesson: ExternalBlob;
}> {
    return {
        id: value.id,
        subject: from_candid_Subject_n28(_uploadFile, _downloadFile, value.subject),
        video: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.video),
        name: value.name,
        level: from_candid_Level_n32(_uploadFile, _downloadFile, value.level),
        solution: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.solution),
        lesson: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.lesson)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    answered: null;
} | {
    not_answered: null;
}): DoubtStatus {
    return "in_progress" in value ? DoubtStatus.in_progress : "answered" in value ? DoubtStatus.answered : "not_answered" in value ? DoubtStatus.not_answered : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biology: null;
} | {
    nature_in_society: null;
} | {
    economy: null;
} | {
    arts: null;
} | {
    world_orientation: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    chemistry: null;
} | {
    german: null;
} | {
    mathematics: null;
} | {
    social_studies: null;
} | {
    physics: null;
} | {
    english: null;
}): Subject {
    return "biology" in value ? Subject.biology : "nature_in_society" in value ? Subject.nature_in_society : "economy" in value ? Subject.economy : "arts" in value ? Subject.arts : "world_orientation" in value ? Subject.world_orientation : "history" in value ? Subject.history : "geography" in value ? Subject.geography : "chemistry" in value ? Subject.chemistry : "german" in value ? Subject.german : "mathematics" in value ? Subject.mathematics : "social_studies" in value ? Subject.social_studies : "physics" in value ? Subject.physics : "english" in value ? Subject.english : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    elementary: null;
} | {
    high: null;
} | {
    middle: null;
}): Level {
    return "elementary" in value ? Level.elementary : "high" in value ? Level.high : "middle" in value ? Level.middle : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoubtEntry>): Promise<Array<DoubtEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DoubtEntry_n10(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Promise<Array<Note>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Note_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n47(_uploadFile, _downloadFile, x)));
}
function to_candid_Difficulty_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_DoubtStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoubtStatus): _DoubtStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Level_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): _Level {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<Subject>;
    savedNotes: Array<string>;
    name: string;
    learningHistory: Array<string>;
    classLevel: Level;
}): {
    subjects: Array<_Subject>;
    savedNotes: Array<string>;
    name: string;
    learningHistory: Array<string>;
    classLevel: _Level;
} {
    return {
        subjects: to_candid_vec_n51(_uploadFile, _downloadFile, value.subjects),
        savedNotes: value.savedNotes,
        name: value.name,
        learningHistory: value.learningHistory,
        classLevel: to_candid_Level_n22(_uploadFile, _downloadFile, value.classLevel)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    biology: null;
} | {
    nature_in_society: null;
} | {
    economy: null;
} | {
    arts: null;
} | {
    world_orientation: null;
} | {
    history: null;
} | {
    geography: null;
} | {
    chemistry: null;
} | {
    german: null;
} | {
    mathematics: null;
} | {
    social_studies: null;
} | {
    physics: null;
} | {
    english: null;
} {
    return value == Subject.biology ? {
        biology: null
    } : value == Subject.nature_in_society ? {
        nature_in_society: null
    } : value == Subject.economy ? {
        economy: null
    } : value == Subject.arts ? {
        arts: null
    } : value == Subject.world_orientation ? {
        world_orientation: null
    } : value == Subject.history ? {
        history: null
    } : value == Subject.geography ? {
        geography: null
    } : value == Subject.chemistry ? {
        chemistry: null
    } : value == Subject.german ? {
        german: null
    } : value == Subject.mathematics ? {
        mathematics: null
    } : value == Subject.social_studies ? {
        social_studies: null
    } : value == Subject.physics ? {
        physics: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): {
    elementary: null;
} | {
    high: null;
} | {
    middle: null;
} {
    return value == Level.elementary ? {
        elementary: null
    } : value == Level.high ? {
        high: null
    } : value == Level.middle ? {
        middle: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoubtStatus): {
    in_progress: null;
} | {
    answered: null;
} | {
    not_answered: null;
} {
    return value == DoubtStatus.in_progress ? {
        in_progress: null
    } : value == DoubtStatus.answered ? {
        answered: null
    } : value == DoubtStatus.not_answered ? {
        not_answered: null
    } : value;
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Subject>): Array<_Subject> {
    return value.map((x)=>to_candid_Subject_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
